name: CI
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  unit-and-sanity-tests:
    name: Unit and sanity tests (py${{ matrix.python }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python:
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
    defaults:
      run:
        working-directory: ansible_collections/
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          path: ansible_collections/redhatinsights/eda

      - name: Set up Python ${{ matrix.ansible }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - name: Install ansible
        run: python -m pip install ansible

      - name: Run sanity tests
        run: ansible-test sanity
        working-directory: ansible_collections/redhatinsights/eda

      - name: Run unit tests
        run: ansible-test units --venv
        working-directory: ansible_collections/redhatinsights/eda

  lint:
    name: Lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ansible_collections/
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          path: ansible_collections/redhatinsights/eda

      - name: Install ansible
        run: python -m pip install ansible-lint

      - name: Install ansible.posix
        run: ansible-galaxy collection install ansible.posix

      - name: Run ansible-lint
        run: ansible-lint
        working-directory: ansible_collections/redhatinsights/eda

  tox-eda-testing:
    name: EDA Partner Testing (Tox)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ansible_collections/
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          path: ansible_collections/redhatinsights/eda

      - name: Install deps
        run: python -m pip install tox
      - name: Run tox
        working-directory: ansible_collections/redhatinsights/eda
        run: |
          python -m tox
